
spring:
  application:
    name: artiexh-api
  datasource:
    url: jdbc:mariadb://${DB_URL:}/artiexh_backend
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    hikari:
      auto-commit: false
  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST:}
      port: ${REDIS_PORT:}
#      password: ${REDIS_PASSWORD}
  jackson:
    default-property-inclusion: non_null
  main:
    allow-circular-references: true
server:
  error:
    include-message: always
    include-stacktrace: never
    whitelabel:
      enabled: false
  port: ${API_SERVER_PORT:}
springdoc:
  show-actuator: true
  swagger-ui:
    path: /swagger-ui
    disable-swagger-default-url: true
    csrf:
      enabled: true
artiexh:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      issuer: http://artiexh.com/api/
      audiences:
        - http://artiexh.com/
        - http://localhost:8080/
    recent_oauth2_fail_id:
      expiration: ${CACHE_RECENT_OAUTH2_FAIL_ID_EXPIRE:}
