spring:
  application:
    name: artiexh-authorization-client
  datasource:
    url: jdbc:mariadb://localhost:3306/artiexh_backend
    username: artiexh-backend
    password: artiexh@123
    type: io.agroal.springframework.boot.AgroalDataSource
    agroal:
      auto-commit: false
  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  data:
    redis:
      host: "localhost"
      port: 6379
      password: artiexh@123
  jackson:
    serialization:
      write-dates-as-timestamps: true
      write-date-timestamps-as-nanoseconds: false
    deserialization:
      read-date-timestamps-as-nanoseconds: false
    default-property-inclusion: non_null
  main:
    allow-circular-references: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 439778912071-u1dajb2a9r49piflunr86vnipeplbig8.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
server:
  error:
    include-message: always
    include-stacktrace: never
    whitelabel:
      enabled: false
artiexh:
  security:
    jwt:
      secret-key: artiexh@123
      issuer: http://artiexh.com/api/
      audiences:
        - http://artiexh.com/
        - http://localhost:8080/
      access-token-expiration: 30
      refresh-token-expiration: 43200
