spring:
  application:
    name: artiexh-api
  datasource:
    url: jdbc:mariadb://${DB_URL:localhost:3306}/artiexh_backend
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:013845}
    hikari:
      auto-commit: false
  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
  jackson:
    serialization:
      write-dates-as-timestamps: true
      write-date-timestamps-as-nanoseconds: false
    deserialization:
      read-date-timestamps-as-nanoseconds: false
    default-property-inclusion: non_null
  main:
    allow-circular-references: true
server:
  error:
    include-message: always
    include-stacktrace: never
    whitelabel:
      enabled: false
springdoc:
  show-actuator: true
  swagger-ui:
    path: /swagger-ui
    disable-swagger-default-url: true
    csrf:
      enabled: true
artiexh:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      issuer: http://artiexh.com/api/
      audiences:
        - http://artiexh.com/
        - http://localhost:8080/
    recent_oauth2_fail_id:
      expiration: ${CACHE_RECENT_OAUTH2_FAIL_ID_EXPIRE:5}
